import { useEffect, useRef, useState } from "react";
import { useParams } from "react-router-dom";
import api from "../../services/api";
import { dateText, downloadElementAsPdf, money } from "../../utils/document";

export default function FinalServiceChallan() {
  const { id } = useParams();
  const paper = useRef<HTMLDivElement>(null);
  const [data, setData] = useState<any>(null);
  useEffect(() => { if (id) api.get(`/services/${id}/document/final`).then((response) => setData(response.data?.data)).catch(console.error); }, [id]);
  if (!data) return <div className="p-6">Loading service challan...</div>;
  const { company, service, template_config: config } = data;
  const asset = service.asset || {};
  return <div className="min-h-screen bg-slate-100 p-4 print:bg-white print:p-0"><div className="no-print mx-auto mb-4 flex max-w-[210mm] justify-end gap-2"><button onClick={() => window.print()} className="rounded bg-slate-800 px-4 py-2 text-sm font-semibold text-white">Print</button><button onClick={() => paper.current && downloadElementAsPdf(paper.current, `${service.service_number}-service-challan.pdf`)} className="rounded bg-blue-600 px-4 py-2 text-sm font-semibold text-white">Download PDF</button></div><article ref={paper} className="mx-auto min-h-[297mm] max-w-[210mm] bg-white p-[16mm] text-sm text-slate-800 shadow print:shadow-none">
    {config.show_header && <header className="flex items-start justify-between border-b-2 border-slate-900 pb-5"><div className="flex gap-4">{config.show_logo && company?.logo_path && <img src={company.logo_path} alt="Company logo" className="h-16 w-16 object-contain" />}<div><h1 className="text-xl font-bold">{company?.company_name}</h1><p>{company?.address}, {company?.city}, {company?.state} {company?.pincode}</p><p>{company?.phone} | {company?.email}</p><p>GSTIN: {company?.gstin || "-"}</p></div></div><div className="text-right"><h2 className="text-2xl font-bold">SERVICE CHALLAN</h2><p className="mt-2">Service No: <b>{service.service_number}</b></p><p>Customer Reference: <b>{service.service_number}</b></p></div></header>}
    {config.show_customer && <section className="my-5 grid grid-cols-2 gap-6"><div><h3 className="mb-2 font-bold uppercase">Customer Details</h3><p className="font-semibold">{service.customer?.company_name}</p><p>{service.contact_person || service.customer?.contact_person}</p><p>Phone: {service.phone || service.customer?.mobile}</p><p>{service.customer?.address}, {service.customer?.city}, {service.customer?.state}</p></div><div><h3 className="mb-2 font-bold uppercase">Completion Details</h3><p>Completion Date: {dateText(service.actual_delivery_date || new Date().toISOString())}</p><p>Technician: {service.service_engineer || service.assigned_technician?.name || "-"}</p></div></section>}
    {config.show_device && <section className="border-y border-slate-300 py-4"><h3 className="mb-2 font-bold uppercase">Device Details</h3><div className="grid grid-cols-2 gap-3"><p>Device: {service.device_type || asset.device_type || "-"}</p><p>Brand / Model: {service.brand || asset.brand || "-"} / {service.model || asset.model || "-"}</p><p>Serial Number: {service.serial_number || asset.serial_number || "-"}</p><p>Complaint: {service.customer_complaint || "-"}</p></div></section>}
    {(config.show_diagnosis || config.show_work_done) && <section className="grid grid-cols-2 gap-5 border-b border-slate-300 py-4">{config.show_diagnosis && <div><h3 className="mb-2 font-bold uppercase">Diagnosis</h3><p className="whitespace-pre-line">{service.technician_diagnosis || "-"}</p></div>}{config.show_work_done && <div><h3 className="mb-2 font-bold uppercase">Work Done</h3><p className="whitespace-pre-line">{service.work_done || "-"}</p></div>}</section>}
    {config.show_spares && <section className="py-4"><h3 className="mb-2 font-bold uppercase">Spare Details</h3><table className="w-full border-collapse"><thead><tr className="bg-slate-900 text-left text-white"><th className="p-2">Spare/Product</th><th className="p-2">Qty</th><th className="p-2 text-right">Rate</th><th className="p-2 text-right">Discount</th><th className="p-2 text-right">Taxable</th><th className="p-2 text-right">GST</th><th className="p-2 text-right">Total</th></tr></thead><tbody>{(service.spares || []).map((spare: any) => <tr key={spare.id} className="border-b border-slate-200"><td className="p-2">{spare.product?.product_name || "-"}</td><td className="p-2">{spare.quantity}</td><td className="p-2 text-right">₹ {money(spare.rate)}</td><td className="p-2 text-right">₹ {money(spare.discount_amount)}</td><td className="p-2 text-right">₹ {money(spare.taxable_amount)}</td><td className="p-2 text-right">₹ {money(spare.gst_amount)}</td><td className="p-2 text-right">₹ {money(spare.total_amount)}</td></tr>)}</tbody></table></section>}
    {config.show_charges && <section className="ml-auto w-80 border-t border-slate-900 pt-3"><p className="flex justify-between">Labour Charge <b>₹ {money(service.labour_charge)}</b></p><p className="flex justify-between">Service Charge <b>₹ {money(service.other_charge)}</b></p><p className="flex justify-between">Discount <b>₹ {money(service.discount_amount)}</b></p><p className="flex justify-between">GST <b>₹ {money(service.gst_amount)}</b></p><p className="mt-2 flex justify-between border-t border-slate-900 pt-2 text-base font-bold">TOTAL AMOUNT <b>₹ {money(service.grand_total)}</b></p></section>}
    {config.show_signature && <section className="mt-16 grid grid-cols-2 gap-12"><div className="border-t border-slate-500 pt-2">Customer Signature</div><div className="border-t border-slate-500 pt-2">Authorized Signature</div></section>}{config.show_footer && <footer className="mt-10 border-t border-slate-900 pt-2 text-center text-xs">{config.footer_text}</footer>}
  </article></div>;
}
