import { useEffect, useMemo, useState } from 'react';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import api from '../../services/api';

type ReportData = { company?: any; summary: Record<string, number>; invoices: any[]; hsn_summary: any[]; rate_summary: any[] };
const money = (value: unknown) => Number(value ?? 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const currentYear = () => { const now = new Date(); const start = now.getMonth() + 1 >= 4 ? now.getFullYear() : now.getFullYear() - 1; return `${start}-${String(start + 1).slice(-2)}`; };
const esc = (value: unknown) => String(value ?? '').replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');

export default function MonthlyTaxInvoiceGSTReport() {
  const [data, setData] = useState<ReportData | null>(null);
  const [financialYear, setFinancialYear] = useState(currentYear());
  const [month, setMonth] = useState(String(new Date().getMonth() + 1));
  const [fromDate, setFromDate] = useState('');
  const [toDate, setToDate] = useState('');
  const [classification, setClassification] = useState('all');
  const [search, setSearch] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const paperId = 'gst-report-paper';

  const load = async () => {
    setLoading(true); setError('');
    try {
      const response = await api.get('/reports/gst/tax-invoices', { params: { financial_year: financialYear || undefined, month: month || undefined, from_date: fromDate || undefined, to_date: toDate || undefined, classification, search: search || undefined } });
      setData(response.data?.data ?? null);
    } catch (requestError: any) { setError(requestError?.response?.data?.message || requestError?.message || 'Unable to load GST report.'); }
    finally { setLoading(false); }
  };
  useEffect(() => { void load(); }, [financialYear, month, fromDate, toDate, classification]);

  const visibleInvoices = useMemo(() => data?.invoices ?? [], [data]);
  const summary = data?.summary;
  const downloadPdf = async () => { const element = document.getElementById(paperId); if (!element) return; const canvas = await html2canvas(element, { scale: 2, backgroundColor: '#fff' }); const pdf = new jsPDF('p', 'mm', 'a4'); const width = 210; const height = canvas.height * width / canvas.width; pdf.addImage(canvas.toDataURL('image/jpeg', .95), 'JPEG', 0, 0, width, height); pdf.save(`monthly-tax-gst-report-${financialYear}.pdf`); };
  const exportExcel = () => {
    const sheet = (name: string, headers: string[], rows: any[]) => `<Worksheet ss:Name="${esc(name)}"><Table><Row>${headers.map((header) => `<Cell><Data ss:Type="String">${esc(header)}</Data></Cell>`).join('')}</Row>${rows.map((row) => `<Row>${row.map((value: unknown) => `<Cell><Data ss:Type="String">${esc(value)}</Data></Cell>`).join('')}</Row>`).join('')}</Table></Worksheet>`;
    const xml = `<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">${sheet('Monthly Summary', ['Metric', 'Value'], [['Total Tax Invoices', summary?.total_tax_invoices], ['Total Taxable Value', summary?.total_taxable_value], ['Total CGST', summary?.total_cgst], ['Total SGST', summary?.total_sgst], ['Total IGST', summary?.total_igst], ['Total GST', summary?.total_gst], ['Total Invoice Value', summary?.total_invoice_value]])}${sheet('Invoice Register', ['Invoice Date', 'Invoice Number', 'Customer Name', 'Customer GSTIN', 'Place of Supply', 'Taxable Value', 'CGST', 'SGST', 'IGST', 'Total GST', 'Grand Total'], visibleInvoices.map((row) => [row.sale_date, row.invoice_no, row.customer_name, row.customer_gstin, row.place_of_supply, row.taxable_value, row.cgst, row.sgst, row.igst, row.total_gst, row.grand_total]))}${sheet('HSN/SAC Summary', ['HSN/SAC', 'Description', 'Quantity', 'Taxable Value', 'GST Rate', 'CGST', 'SGST', 'IGST', 'Total GST', 'Total Value'], (data?.hsn_summary ?? []).map((row) => [row.hsn_sac, row.description, row.quantity, row.taxable_value, row.gst_rate, row.cgst, row.sgst, row.igst, row.total_gst, row.total_value]))}${sheet('GST Rate Summary', ['GST Rate', 'Taxable Value', 'CGST', 'SGST', 'IGST', 'Total GST', 'Total Value'], (data?.rate_summary ?? []).map((row) => [row.gst_rate, row.taxable_value, row.cgst, row.sgst, row.igst, row.total_gst, row.total_value]))}</Workbook>`;
    const blob = new Blob([xml], { type: 'application/vnd.ms-excel' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `monthly-tax-gst-report-${financialYear}.xls`; link.click(); URL.revokeObjectURL(link.href);
  };

  return <section className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-semibold uppercase tracking-wide text-blue-600">Reports / GST Reports</p><h1 className="text-3xl font-bold text-slate-900">Monthly Tax Invoice GST Report</h1><p className="text-sm text-slate-500">Tax invoices only. Generated from existing sales transactions.</p></div><div className="flex gap-2 print:hidden"><button onClick={() => window.print()} className="rounded border bg-white px-4 py-2 text-sm font-semibold">Print</button><button onClick={() => void downloadPdf()} className="rounded border bg-white px-4 py-2 text-sm font-semibold">Download PDF</button><button onClick={exportExcel} disabled={!data} className="rounded bg-emerald-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Export Excel</button></div></div>
    <div className="rounded-xl border bg-white p-5 shadow-sm print:hidden"><div className="grid gap-4 md:grid-cols-5"><label className="text-sm font-medium">Financial Year<input value={financialYear} onChange={(e) => setFinancialYear(e.target.value)} placeholder="2026-27" className="mt-1 w-full rounded border p-2" /></label><label className="text-sm font-medium">Month<select value={month} onChange={(e) => setMonth(e.target.value)} className="mt-1 w-full rounded border p-2"><option value="">All months</option>{Array.from({ length: 12 }, (_, index) => <option key={index + 1} value={index + 1}>{new Date(2000, index).toLocaleString('en-IN', { month: 'long' })}</option>)}</select></label><label className="text-sm font-medium">From Date<input type="date" value={fromDate} onChange={(e) => setFromDate(e.target.value)} className="mt-1 w-full rounded border p-2" /></label><label className="text-sm font-medium">To Date<input type="date" value={toDate} onChange={(e) => setToDate(e.target.value)} className="mt-1 w-full rounded border p-2" /></label><label className="text-sm font-medium">Search<input value={search} onChange={(e) => setSearch(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && void load()} placeholder="Invoice, customer, GSTIN" className="mt-1 w-full rounded border p-2" /></label></div><div className="mt-4 flex gap-2"><button onClick={() => setClassification('all')} className={`rounded px-4 py-2 text-sm font-semibold ${classification === 'all' ? 'bg-slate-900 text-white' : 'bg-slate-100'}`}>ALL</button><button onClick={() => setClassification('b2b')} className={`rounded px-4 py-2 text-sm font-semibold ${classification === 'b2b' ? 'bg-blue-600 text-white' : 'bg-slate-100'}`}>B2B</button><button onClick={() => setClassification('b2c')} className={`rounded px-4 py-2 text-sm font-semibold ${classification === 'b2c' ? 'bg-blue-600 text-white' : 'bg-slate-100'}`}>B2C</button><button onClick={() => void load()} className="ml-auto rounded border px-4 py-2 text-sm font-semibold">Apply</button></div></div>
    {error && <div className="rounded border border-red-200 bg-red-50 p-4 text-red-700">{error}</div>}
    {loading ? <p>Loading GST report...</p> : data && <div id={paperId} className="space-y-6 bg-white print:p-6"><header className="border-b-2 border-slate-900 pb-4"><h2 className="text-xl font-bold">{data.company?.company_name || 'AGS-ERP'}</h2><p>{data.company?.address || '-'} {data.company?.city || ''} {data.company?.state || ''}</p><p>GSTIN: {data.company?.gstin || '-'} {data.company?.pan ? `· PAN: ${data.company.pan}` : ''}</p><h3 className="mt-4 text-center text-2xl font-bold">MONTHLY TAX INVOICE GST REPORT</h3><p className="text-center text-sm">Financial Year: {financialYear} · Period: {month ? new Date(2000, Number(month) - 1).toLocaleString('en-IN', { month: 'long' }) : 'All Months'} · Generated: {new Date().toLocaleDateString('en-IN')}</p></header>
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Total Tax Invoices', summary?.total_tax_invoices], ['Taxable Value', summary?.total_taxable_value], ['CGST', summary?.total_cgst], ['SGST', summary?.total_sgst], ['IGST', summary?.total_igst], ['Total GST', summary?.total_gst], ['Invoice Value', summary?.total_invoice_value]].map(([label, value]) => <div className="rounded border p-3" key={String(label)}><p className="text-xs text-slate-500">{label}</p><p className="text-lg font-bold">{typeof value === 'number' && label !== 'Total Tax Invoices' ? `₹ ${money(value)}` : value ?? 0}</p></div>)}</div>
      <ReportTable title="Invoice Register" headers={['Invoice Date', 'Invoice Number', 'Customer Name', 'Customer GSTIN', 'Place of Supply', 'Taxable Value', 'CGST', 'SGST', 'IGST', 'Total GST', 'Grand Total']} rows={visibleInvoices.map((row) => [row.sale_date, row.invoice_no, row.customer_name, row.customer_gstin, row.place_of_supply, `₹ ${money(row.taxable_value)}`, `₹ ${money(row.cgst)}`, `₹ ${money(row.sgst)}`, `₹ ${money(row.igst)}`, `₹ ${money(row.total_gst)}`, `₹ ${money(row.grand_total)}`])} />
      <ReportTable title="HSN/SAC Summary" headers={['HSN/SAC', 'Description', 'Quantity', 'Taxable Value', 'GST Rate', 'CGST', 'SGST', 'IGST', 'Total GST', 'Total Value']} rows={(data.hsn_summary ?? []).map((row) => [row.hsn_sac, row.description, row.quantity, `₹ ${money(row.taxable_value)}`, `${row.gst_rate}%`, `₹ ${money(row.cgst)}`, `₹ ${money(row.sgst)}`, `₹ ${money(row.igst)}`, `₹ ${money(row.total_gst)}`, `₹ ${money(row.total_value)}`])} />
      <ReportTable title="GST Rate Summary" headers={['GST Rate', 'Taxable Value', 'CGST', 'SGST', 'IGST', 'Total GST', 'Total Value']} rows={(data.rate_summary ?? []).map((row) => [`${row.gst_rate}%`, `₹ ${money(row.taxable_value)}`, `₹ ${money(row.cgst)}`, `₹ ${money(row.sgst)}`, `₹ ${money(row.igst)}`, `₹ ${money(row.total_gst)}`, `₹ ${money(row.total_value)}`])} />
      {!visibleInvoices.length && <p className="py-6 text-center text-slate-500">No Tax Invoices Found</p>}</div>}
  </section>;
}

function ReportTable({ title, headers, rows }: { title: string; headers: string[]; rows: unknown[][] }) { return <section><h2 className="mb-2 text-lg font-bold">{title}</h2><div className="overflow-x-auto rounded border"><table className="min-w-full text-left text-xs"><thead className="bg-slate-900 text-white"><tr>{headers.map((header) => <th className="whitespace-nowrap px-3 py-2" key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr className="border-b" key={index}>{row.map((value, cellIndex) => <td className="whitespace-nowrap px-3 py-2" key={cellIndex}>{String(value ?? '-')}</td>)}</tr>)}</tbody></table></div></section>; }
